steps:
- uses: actions/checkout@v4
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.7'
- name: Lint with Ruff
  run: |
    pip install ruff
    ruff --output-format=github --target-version=py37 .
  continue-on-error: true
